<a href="https://colab.research.google.com/github/dlsdnsms/Data-Analysis-with-Open-Source/blob/main/%EC%98%A4%ED%94%88%EC%86%8C%EC%8A%A4_%EB%8D%B0%EC%9D%B4%ED%84%B0_%EB%B6%84%EC%84%9D_2%EA%B0%95.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>



# 오픈소스 기반 데이터 분석 2강 - 데이터 분석을 위한 파이썬 1

## 2-1 리스트 슬라이싱

In [73]:
import requests
import time
import pandas as pd

url = "http://openapi.seoul.go.kr:8088"
api_key = "447a456b6c646c7332376747714374"
TYPE = "json"
SERVICE = "energyUseDataSummaryInfo"
START_INDEX = "1"
END_INDEX = "1000"

data = []


for year in range(2015, 2025):
    year = f"{year:04d}"
    for month in range(1, 13):
        month = f"{month:02d}"
        api_url=f"{url}/{api_key}/{TYPE}/{SERVICE}/{START_INDEX}/{END_INDEX}/{year}/{month}"
        response = requests.get(api_url)

        result = response.json()['energyUseDataSummaryInfo']['row']

        for a in result:
            if a.get('MM_TYPE') == "개인":
                data.append({
                    "유형" : a.get("MM_TYPE"),
                    "년도" : a.get("YEAR")
                    "월": a.get("MON"),
                    "전기": a.get("EUS"),
                    "가스": a.get("GUS"),
                    "수도": a.get("WUS"),
                    "지역난방": a.get("HUS")
                })


df = pd.DataFrame(data)
df


       ## requests로부터 response, body, item 항목 읽기


#print(len(data))
#print(data[0])
#df = pd.DataFram(data)

#df['칼럼'] > 해당 열만 추출

     유형    년도
0    개인  2015
1    개인  2015
2    개인  2015
3    개인  2015
4    개인  2015
..   ..   ...
115  개인  2024
116  개인  2024
117  개인  2024
118  개인  2024
119  개인  2024

[120 rows x 2 columns]

In [ ]:
import requests
import time
import pandas as pd

url = "http://openapi.seoul.go.kr:8088"
api_key = "447a456b6c646c7332376747714374"
TYPE = "json"
SERVICE = "energyUseDataSummaryInfo"
START_INDEX = "1"
END_INDEX = "1000"


for year in range(2015, 2025):
    year = f"{year:04d}"
    for month in range(1, 13):
        month = f"{month:02d}"
        api_url=f"{url}/{api_key}/{TYPE}/{SERVICE}/{START_INDEX}/{END_INDEX}/{year}/{month}"
        response = requests.get(api_url)

        data = response.json()['energyUseDataSummaryInfo']['row']




        df = pd.DataFrame(data)
        df = df[df['MM_TYPE'] == '개인']

        display(df[['MM_TYPE','YEAR', 'MON', 'EUS', 'GUS', 'WUS', 'HUS']].style.hide(axis="index"))


       ## requests로부터 response, body, item 항목 읽기


#print(len(data))
#print(data[0])
#df = pd.DataFram(data)

#df['칼럼'] > 해당 열만 추출

In [ ]:
numbers = [10, 20, 30, 40, 50, 60, 70]

# 홀수번째 항목 출력

print(every_other_list)

# 역순 출력

print(reverse_list)

In [ ]:
matrix = [
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
]

# 첫 두 행 출력


print(first_two_rows)

# 첫 두 열 출력


print(first_two_columns)

## 2-2 리스트 컴프리헨션

In [ ]:
numbers = [ ]

# 1 ~ 5 포함 리스트 생성
for i in range(5):
    numbers.append(i)

print(numbers)

In [ ]:
numbers = [1, 2, 3, 4, 5]
squares = [ ]

# numbers의 모든 항목의 값을 제곱한 리스트
for num in numbers:
  squares.append(num ** 2)

print(squares)

In [ ]:
numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
even_numbers = [ ]

# 짝수만 추출한 리스트
for num in numbers:
    if num % 2 == 0:
        even_numbers.append(num)

print(even_numbers)

In [ ]:
list1 = ['사과', '복숭아', '바나나']
list2 = ['주스', '잼', '통조림']
pairs = [ ]

# 두 리스트에 포함되 모든 원소를 조합한 투플의 리스트 생성
for fruit in list1:
    for product in list2:
        pairs.append((fruit, product))

print(pairs)

In [ ]:
squares = { }

# 딕셔너리 생성
for i in range(5):
    squares[i] = i ** 2

print(squares)

In [ ]:
city_population = {
    '서울': 957, '부산': 339, '인천': 294, '대구': 242, '광주': 145, '대전': 147,
    '울산': 114, '세종': 36, '수원': 115, '창원': 103, '고양': 105, '용인': 108, '성남': 94
}

# 인구 200만명 이상의 도시 리스트

print(large_cities)

# 인구 300만 이상 및 이름에 '산'이 포함된 도시 리스트

print(large_short_name_cities)

## 2-3 문자열 형식화

In [ ]:
name = '홍길동'
age = 30
salary = 3500000
tax_rate = 0.1

# C 스타일 문자열 포매팅
# 이름, 나이, 월급 출력

# 직원이름, 나이, 세후 월급 출력


# 직원이름, 나이, 월급, 세금, 실수령액 추력


print(basic_format)
print(index_format)
print(keyword_format)

In [ ]:
name = '홍길동'
age = 30
salary = 3500000
tax_rate = 0.1

# str.format 문자열 포매팅
# 이름, 나이, 월급 출력

# 직원이름, 나이, 세후 월급 출력

# 직원이름, 나이, 월급, 세금, 실수령액 추력


print(basic_format)
print(index_format)
print(keyword_format)

In [ ]:
name = '홍길동'
age = 30
salary = 3500000
tax_rate = 0.1

# f-문자열 포매팅
# 이름, 나이, 월급 출력

# 직원이름, 나이, 세후 월급 출력

# 직원이름, 나이, 월급, 세금, 실수령액 추력


print(basic_format)
print(index_format)
print(keyword_format)

## 2-4 컨텍스트 관리

In [ ]:
# 파일 오픈 & 클로즈
file = open('output.txt', 'w')
file.write('Hello, world!\n')

In [ ]:
# 복수개의 파일(읽기 & 쓰기) 관리

In [ ]:
import urllib.request

# URL 연결 관리
('https://raw.githubusercontent.com/jaehwachung/Data-Analysis-with-Open-Source/refs/heads/main/Chapter%203/students.csv')
    data = response.read( ).decode('utf-8')

print(data)